---
# SECURITY CHECK SCRIPT - last updated 09/20/2021
- name: run web config file checks
  hosts: testserver
  become: yes

  roles:
    - web_config


- name: run network security checks
  hosts: testserver
  become: yes

  roles:
    - network_sec
