---
- name: list all users on box
  command: getend passwd | grep /bin/bash
  register: users

- debug: msg="{{ users.stdout }}" 


- name: PAM Auth secure -> 1/2
  lineinfile:
    path: /etc/pam.d/password-auth
    state: present
    regexp: '^{{ item }}'
  loop: 
    - "auth required pam_env.so"
    - "auth required pam_faillock.so preauth audit silent deny=5 unlock_time=604800"
    - "auth [success=1 default=bad] pam_unix.so"
    - "auth [default=die] pam_faillock.so authfail audit deny=5 unlock_time=604800"
    - "auth sufficient pam_faillock.so authsucc audit deny=5 unlock_time=604800"
    - "auth required pam_deny.so"


- name: PAM Auth secure -> 2/2
  lineinfile:
    path: /etc/pam.d/system-auth
    state: present
    regexp: '^{{ item }}'
  loop: 
    - "auth required pam_env.so"
    - "auth required pam_faillock.so preauth audit silent deny=5 unlock_time=604800"
    - "auth [success=1 default=bad] pam_unix.so"
    - "auth [default=die] pam_faillock.so authfail audit deny=5 unlock_time=604800"
    - "auth sufficient pam_faillock.so authsucc audit deny=5 unlock_time=604800"
    - "auth required pam_deny.so"