---
- name: list firewall rules
  command: "firewall-cmd --list-all"
  register: rules

- debug: msg="{{ rules.stdout }}"


- name: list open ports
  command: "netstat -tulpn"
  register: ports

# open ports command output
- debug: msg="{{ ports.stdout }}" 

- name: permit httpd traffic 
  ansible.posix.firewalld:
    port: 9001/tcp
    permanent: yes
    state: enabled

- name: permit ssh traffic
  ansible.posix.firewalld:
    port: 22/tcp
    permanent: yes
    state: enabled
    

