---
# for descriptions of each task, view the '- name' section
- name: make sure httpd is updated, update if not 
  yum:
    name: httpd
    state: latest


- name: check for Apache version hiding
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'ServerSignature Off'
    - 'ServerTokens Prod'


- name: check for Apache directory structure hiding
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'Options -Indexes'
    - 'AllowOverride None'
    - 'Require all granted'


- name: check for unnessary modules
  lineinfile:
    path: /etc/httpd/conf.module.d/00-base.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - '#LoadModule info_module modules/mod_info.so'
    - '#LoadModule info_module modules/mod_info.so'
    - '#LoadModule userdir_module modules/mod_userdir.so'


- name: "make sure symlinks aren't followed"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'Options -Indexes -FollowSymLinks'
    - 'AllowOverride None'
    - 'Require all granted'


- name: "checking for SSI and CGI enabled"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'Options -Indexes -FollowSymLinks -ExecCGI -Includes'
    - 'AllowOverride None'
    - 'Require all granted'


- name: "limit request sizes"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'LimitRequestBody 204800'


- name: "check for browsing away from document root"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'Options None'
    - 'Order deny,allow'
    - 'Deny from all'


- name: "check for clickjacking possibilites"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'Header append X-FRAME-OPTIONS "SAMEORIGIN"'


- name: "check for ETAG possibilites"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'FileETag None'


- name: "check for HTTP pruning possibilites"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'deny from all'


- name: "check for XSS pruning possibilites"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'Header set X-XSS-Protection "1; mode=block"'


- name: "check for HTTPOnly Flag"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  failed_when: presence is changed 
  with_items:
    - 'Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure'
