---
# for descriptions of each task, view the '- name' section
- name: make sure httpd is updated, update if not 
  yum:
    name: httpd
    state: latest


- name: check for Apache version hiding
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'ServerSignature Off'
    - 'ServerTokens Prod'
- fail: 
    msg: "Policies missing, check security policies for Apache Version Hiding"
  when: presence is changed



- name: check for Apache directory structure hiding
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  with_items:
    - 'Options -Indexes'
    - 'AllowOverride None'
    - 'Require all granted'
- fail: 
    msg: "Policies missing, check security policies for Apache Directory Structure Hiding"
  when: presence is changed


- name: check for unnecessary modules
  lineinfile:
    path: /etc/httpd/conf.module.d/00-base.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - '#LoadModule info_module modules/mod_info.so'
    - '#LoadModule info_module modules/mod_info.so'
    - '#LoadModule userdir_module modules/mod_userdir.so'
- fail: 
    msg: "Policies missing, check security policies for uncessary modules"
  when: presence is changed


- name: "make sure symlinks aren't followed"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'Options -Indexes -FollowSymLinks'
    - 'AllowOverride None'
    - 'Require all granted'
- fail: 
    msg: "Policies missing, check security policies for symlink following"
  when: presence is changed


- name: "checking for SSI and CGI enabled"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'Options -Indexes -FollowSymLinks -ExecCGI -Includes'
    - 'AllowOverride None'
    - 'Require all granted'
- fail: 
    msg: "Policies missing, check security policies for SSI + CGI disabling"
  when: presence is changed


- name: "limit request sizes"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'LimitRequestBody 204800'
- fail: 
    msg: "Policies missing, check security policies for Apache request size limiting"
  when: presence is changed


- name: "check for browsing away from document root"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'Options None'
    - 'Order deny,allow'
    - 'Deny from all'
- fail: 
    msg: "Policies missing, check security policies for Apache non-root directory browsing"
  when: presence is changed


- name: "check for clickjacking possibilites"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'Header append X-FRAME-OPTIONS "SAMEORIGIN"'
- fail: 
    msg: "Policies missing, check security policies for Apache clickjacking possibilities"
  when: presence is changed


- name: "check for ETAG possibilites"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'FileETag None'
- fail: 
    msg: "Policies missing, check security policies for Apache ETAG possiblilities"
  when: presence is changed


- name: "check for HTTP pruning possibilites"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'deny from all'
- fail: 
    msg: "Policies missing, check security policies for Apache HTTP Pruning"
  when: presence is changed


- name: "check for XSS pruning possibilites"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'Header set X-XSS-Protection "1; mode=block"'
- fail: 
    msg: "Policies missing, check security policies for Apache XSS"
  when: presence is changed


- name: "check for HTTPOnly Flag"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
    state: present
  check_mode: yes
  register: presence
  #failed_when: presence is changed 
  with_items:
    - 'Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure'
- fail: 
    msg: "Policies missing, check security policies for Apache HTTPOnly"
  when: presence is changed
